### ISSUE TITLE
The checkpoint of Charades-STA

### ISSUE THREAD

**Issue by TensorsSun** [mingyao1120/TR-DETR#2]
Excuse me, could you provide the checkpoint of Charades-STA？

**Comment by mingyao1120** [comment]
Sorry, due to non-human reasons, the relevant code based on Charades-STA and according checkpoint cannot be available to obtain at present. Please refer to the following link to reproduce the code implementation on Charade-STA: https://github.com/wjun0830/QD-DETR/issues/1; Sorry for the inconvenience.
